### ISSUE TITLE
Structure changes

### ISSUE THREAD

**Issue by NitinHsharma** [A-Tokyo/apple-signin-auth#34]
Hey @A-Tokyo 

I was thinking of restructuring the code by splitting the functionality into multiple files. **feel free to delete/ignore/deny this suggestion** 

```
-src
    - utils
        - getAuthorizationUrl.js
        - getAuthorizationToken.js
        - refreshAuthorizationToken.js
        - verifyIdToken.js
        - operation.js
    - interface
        -  AppleIdTokenType.js
        -  AppleAuthorizationTokenResponseType.js
    - index.js 
```

index.js will responsible only for exporting the functionality.
operation.js will be responsible for common functions like _getApplePublicKeys, _setFetch. 
remaining files are self-explanatory :)

**Comment by A-Tokyo** [comment]
Hey @NitinHsharma! Thank you so much for your proposal! Really nice notes you got there.

Generally I am a fan of modularization, however, recently Getlify and Dan Abramov brought up a very nice topic about how monofile projects are much easier to manage at the beginning since they focus on the core functionality. They both agreed, and I do as well, that one should start modularizing when one feels the monofile would grow out of hand.

What are your thoughts on this? :rocket:

NOTE: Generally I used the structure you mentioned, however I noticed that with this specific project monofile is so much easier to manage. (specially if we decide to move to typescript)

Your input is highly appreciated!

**Comment by A-Tokyo** [comment]
@Nikosmonaut Quite a nice analysis! ( :

So let's close this for now and reopen it once the project scales a bit? thoughts? 🚀

**Comment by Nikosmonaut** [comment]
Thank you for giving me credit on it :joy:

**Comment by A-Tokyo** [comment]
Ooopssss! 😂 @NitinHsharma! He was Niko was my last at and both if your Names start with NI! 🙈 

Special thanks to the awesome @NitinHsharma 🚀
